# -*- coding: utf-8 -*-
"""- Pydantic schema definitions for key data structures

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Renuka239/fd21dd00375cfea1e2e327453f48e3bb/welcome-to-colab.ipynb
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Literal
from uuid import uuid4

from pydantic import BaseModel, Field, ConfigDict, field_validator

# Type Aliases / Enums
# -----------------------------
ColumnSemanticType = Literal["numeric", "categorical", "datetime", "boolean", "text", "unknown"]
FileFormat = Literal["csv", "excel"]
Severity = Literal["low", "medium", "high", "critical"]

class ColumnSchema(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    dtype_raw: Optional[str] = None
    semantic_type: ColumnSemanticType = "unknown"

    missing_count: int = 0
    missing_ratio: float = 0.0
    unique_count: Optional[int] = None
    is_constant: bool = False
    is_empty: bool = False
    sample_values: Optional[List[Any]] = None


class DatasetSchema(BaseModel):
    model_config = ConfigDict(extra="allow")

    dataset_id: str = Field(default_factory=lambda: str(uuid4()))
    name: str = "uploaded_dataset"
    file_format: FileFormat = "csv"
    source_filename: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)

    row_count: int = 0
    column_count: int = 0
    columns: List[ColumnSchema] = Field(default_factory=list)

    numeric_columns: List[str] = Field(default_factory=list)
    categorical_columns: List[str] = Field(default_factory=list)
    datetime_columns: List[str] = Field(default_factory=list)
    boolean_columns: List[str] = Field(default_factory=list)
    text_columns: List[str] = Field(default_factory=list)
    unknown_columns: List[str] = Field(default_factory=list)

    preview_rows: Optional[List[Dict[str, Any]]] = None

# Quality Report
# -----------------------------
class TypeIssue(BaseModel):
    model_config = ConfigDict(extra="allow")

    column: str
    issue: str
    count: Optional[int] = None
    examples: Optional[List[Any]] = None
    severity: Severity = "medium"


class MissingValueReport(BaseModel):
    model_config = ConfigDict(extra="allow")

    by_column: Dict[str, int] = Field(default_factory=dict)
    total_missing: int = 0
    missing_ratio_overall: float = 0.0  # 0..1


class DuplicateReport(BaseModel):
    model_config = ConfigDict(extra="allow")

    duplicate_row_count: int = 0
    duplicate_row_ratio: float = 0.0  # 0..1

    class OutlierReport(BaseModel):
        model_config = ConfigDict(extra="allow")

        method: Literal["iqr"] = "iqr"
        by_column: Dict[str, int] = Field(default_factory=dict)
        bounds_by_column: Dict[str, Dict[str, float]] = Field(default_factory=dict)


class QualityReport(BaseModel):
    model_config = ConfigDict(extra="allow")

    dataset_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    missing: MissingValueReport = Field(default_factory=MissingValueReport)
    duplicates: DuplicateReport = Field(default_factory=DuplicateReport)
    outliers: Optional[OutlierReport] = None

    empty_columns: List[str] = Field(default_factory=list)
    constant_columns: List[str] = Field(default_factory=list)
    type_issues: List[TypeIssue] = Field(default_factory=list)

    quality_score: Optional[float] = None
    score_scale: Literal["0_100"] = "0_100"

    warnings: List[str] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)

    @field_validator("quality_score")
    @classmethod
    def score_non_negative(cls, v: Optional[float]) -> Optional[float]:
        if v is None:
            return v
        if v < 0:
            raise ValueError("quality_score cannot be negative.")
        return v

# Profile Report
# -----------------------------
class NumericProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    count: int
    mean: Optional[float] = None
    std: Optional[float] = None
    min: Optional[float] = None
    p25: Optional[float] = None
    median: Optional[float] = None
    p75: Optional[float] = None
    max: Optional[float] = None


class CategoricalProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    count: int
    unique: int
    top: Optional[Any] = None
    freq: Optional[int] = None
    top_k: Optional[List[Dict[str, Any]]] = None  # [{"value":..., "count":...}, ...]

    class DatetimeProfile(BaseModel):
        model_config = ConfigDict(extra="allow")

        count: int
        min: Optional[str] = None  # ISO string
        max: Optional[str] = None  # ISO string


class TextProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    count: int
    avg_length: Optional[float] = None
    min_length: Optional[int] = None
    max_length: Optional[int] = None


class ColumnProfile(BaseModel):
    model_config = ConfigDict(extra="allow")

    name: str
    semantic_type: ColumnSemanticType = "unknown"
    missing_count: int = 0
    missing_ratio: float = 0.0
    numeric: Optional[NumericProfile] = None
    categorical: Optional[CategoricalProfile] = None
    datetime: Optional[DatetimeProfile] = None
    text: Optional[TextProfile] = None


class ProfileReport(BaseModel):
    model_config = ConfigDict(extra="allow")

    dataset_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    column_profiles: List[ColumnProfile] = Field(default_factory=list)
    notes: List[str] = Field(default_factory=list)