# -*- coding: utf-8 -*-
"""Error handling with retries and fallbacks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pzc2jpX45RGcRsTcpSXaikz_89NIQj9b
"""

#Error handling with retries + fallbacks for your AI Tableau Generator pipeline.
from __future__ import annotations

import logging
import random
import time
from dataclasses import dataclass
from typing import Any, Callable, Optional, Tuple, Type, Union, Iterable

import pandas as pd

# Import your custom exceptions and Pydantic models
# from your_module import DataProcessor, DataLoadError, DataValidationError
# from schemas import DatasetSchema, QualityReport, ProfileReport, ColumnSchema

logger = logging.getLogger("Resilience")
logger.setLevel(logging.INFO)
if not logger.handlers:
    _h = logging.StreamHandler()
    _h.setFormatter(logging.Formatter("[%(asctime)s] %(levelname)s | %(name)s | %(message)s"))
    logger.addHandler(_h)

# Retry configuration
# -----------------------------

@dataclass(frozen=True)
class RetryPolicy:
    max_attempts: int = 3
    base_delay_s: float = 0.5       # first sleep
    max_delay_s: float = 8.0        # cap
    backoff: float = 2.0            # exponential growth factor
    jitter_s: float = 0.25          # random +/- jitter added to each delay
    retry_on: Tuple[Type[BaseException], ...] = (TimeoutError, ConnectionError)
    # You can add more, e.g. pandas/IO transient issues:
    # retry_on: Tuple[Type[BaseException], ...] = (TimeoutError, ConnectionError, OSError)


def _sleep_with_backoff(attempt: int, policy: RetryPolicy) -> None:
    # attempt is 1-based
    delay = policy.base_delay_s * (policy.backoff ** (attempt - 1))
    delay = min(delay, policy.max_delay_s)
    jitter = random.uniform(-policy.jitter_s, policy.jitter_s)
    time.sleep(max(0.0, delay + jitter))


def retry(
    fn: Callable[[], Any],
    *,
    policy: RetryPolicy,
    op_name: str,
    on_error: Optional[Callable[[BaseException, int], None]] = None,
) -> Any:
    """
    Run fn() with retries.

    - Retries only exceptions in policy.retry_on
    - Raises final exception if all retries fail
    """
    last_exc: Optional[BaseException] = None

    for attempt in range(1, policy.max_attempts + 1):
        try:
            return fn()
        except policy.retry_on as exc:
            last_exc = exc
            if on_error:
                on_error(exc, attempt)

            # last attempt -> re-raise
            if attempt >= policy.max_attempts:
                logger.error("❌ %s failed after %d attempts: %s", op_name, attempt, exc)
                raise

            logger.warning("⚠️ %s failed (attempt %d/%d): %s. Retrying...",
                           op_name, attempt, policy.max_attempts, exc)
            _sleep_with_backoff(attempt, policy)

    # should never hit
    if last_exc:
        raise last_exc
    raise RuntimeError(f"Unexpected retry() state for {op_name}")

# Fallback helpers (load)
# -----------------------------

def safe_read_csv_with_fallbacks(
    file_path: Union[str, "pd.io.common.FilePath"],
    *,
    encodings: Iterable[str] = ("utf-8", "latin-1"),
    policy: RetryPolicy = RetryPolicy(retry_on=(OSError, TimeoutError, ConnectionError)),
) -> pd.DataFrame:
    """
    Fallback behavior:
    - Try encodings in order
    - Retry on IO-like transient errors
    """
    last_exc: Optional[BaseException] = None

    for enc in encodings:
        def _op() -> pd.DataFrame:
            return pd.read_csv(file_path, encoding=enc)

        try:
            df = retry(_op, policy=policy, op_name=f"read_csv(encoding={enc})")
            return df
        except Exception as exc:
            last_exc = exc
            logger.warning("CSV load failed with encoding=%s: %s", enc, exc)

    raise RuntimeError(f"All CSV encoding fallbacks failed. Last error: {last_exc}")


def safe_read_excel_with_fallbacks(
    file_path: Union[str, "pd.io.common.FilePath"],
    *,
    sheet_name: Union[str, int, None] = 0,
    policy: RetryPolicy = RetryPolicy(retry_on=(OSError, TimeoutError, ConnectionError)),
) -> pd.DataFrame:
    """
    Fallback behavior:
    - Try default engine (pandas decides)
    - If it fails, try openpyxl explicitly
    """
    def _default() -> pd.DataFrame:
        return pd.read_excel(file_path, sheet_name=sheet_name)

    try:
        return retry(_default, policy=policy, op_name="read_excel(default)")
    except Exception as exc:
        logger.warning("Default excel engine failed: %s. Trying engine='openpyxl' fallback...", exc)

    def _openpyxl() -> pd.DataFrame:
        return pd.read_excel(file_path, sheet_name=sheet_name, engine="openpyxl")

    return retry(_openpyxl, policy=policy, op_name="read_excel(openpyxl)")

# Pipeline wrapper with fallbacks
# -----------------------------

@dataclass
class PipelineResult:
    """
    A "never crash" result container:
    - df/schema/quality/profile might be None if that stage fails
    - errors/warnings accumulate for UI display (Streamlit etc.)
    """
    df: Optional[pd.DataFrame] = None
    schema: Optional[Any] = None
    quality: Optional[Any] = None
    profile: Optional[Any] = None
    warnings: list[str] = None
    errors: list[str] = None

    def __post_init__(self) -> None:
        if self.warnings is None:
            self.warnings = []
        if self.errors is None:
            self.errors = []


class ResilientPipeline:
    """
    Wraps your DataProcessor with retries + fallbacks.

    Typical usage:
        rp = ResilientPipeline(processor=DataProcessor())
        result = rp.run("train.csv", dataset_name="Train Dataset")
        # result.schema / result.quality / result.profile ready for downstream steps
    """

    def __init__(self, processor: Any):
        self.processor = processor

        # Policies per stage (tune as you like)
        self.load_policy = RetryPolicy(
            max_attempts=3,
            base_delay_s=0.5,
            max_delay_s=6.0,
            backoff=2.0,
            jitter_s=0.3,
            retry_on=(OSError, TimeoutError, ConnectionError),
        )
        self.compute_policy = RetryPolicy(
            max_attempts=2,
            base_delay_s=0.25,
            max_delay_s=2.0,
            backoff=2.0,
            jitter_s=0.2,
            retry_on=(TimeoutError,),  # computation usually shouldn't retry on logic errors
        )

    def run(
        self,
        file_path: Union[str, "pd.io.common.FilePath"],
        *,
        dataset_name: Optional[str] = None,
        source_filename: Optional[str] = None,
        sheet_name: Union[str, int, None] = 0,
    ) -> PipelineResult:
        result = PipelineResult()

        # -------------------------
        # 1) LOAD with fallbacks
        # -------------------------
        try:
            # If you want to use your existing processor.load(), you can wrap that too.
            # But here we provide stronger format-specific fallbacks.
            fp = str(file_path).lower()
            if fp.endswith(".csv"):
                df = safe_read_csv_with_fallbacks(file_path, policy=self.load_policy)
            elif fp.endswith(".xlsx") or fp.endswith(".xls"):
                df = safe_read_excel_with_fallbacks(file_path, sheet_name=sheet_name, policy=self.load_policy)
            else:
                # fallback: try processor.load (it already checks extensions)
                df = retry(lambda: self.processor.load(file_path), policy=self.load_policy, op_name="processor.load")

            # Align with your processor.load() behavior (strip columns)
            df.columns = [str(c).strip() for c in df.columns]
            result.df = df

        except Exception as exc:
            result.errors.append(f"Load failed: {exc}")
            logger.exception("Load stage failed")
            return result  # hard stop (no df -> no pipeline)

        # -------------------------
        # 2) VALIDATE (schema)
        # -------------------------
        try:
            # Validate is mostly deterministic; usually not a good retry candidate
            schema = self.processor.validate(
                result.df,
                source_filename=source_filename,
                dataset_name=dataset_name,
            )
            result.schema = schema

        except Exception as exc:
            # Fallback: build a minimal schema (so UI can still continue)
            result.warnings.append(f"Validate failed; using minimal schema fallback. Reason: {exc}")
            logger.exception("Validate stage failed; falling back to minimal schema")

            result.schema = self._minimal_schema_fallback(
                df=result.df,
                dataset_name=dataset_name or "uploaded_dataset",
                source_filename=source_filename,
            )
# 3) QUALITY (soft fail)
        # -------------------------
        try:
            quality = retry(
                lambda: self.processor.assess_quality(result.df, result.schema),
                policy=self.compute_policy,
                op_name="assess_quality",
            )
            result.quality = quality
        except Exception as exc:
            result.warnings.append(f"Quality assessment skipped due to error: {exc}")
            logger.exception("Quality stage failed (soft)")

        # -------------------------
        # 4) PROFILE (soft fail)
        # -------------------------
        try:
            profile = retry(
                lambda: self.processor.profile(result.df, result.schema),
                policy=self.compute_policy,
                op_name="profile",
            )
            result.profile = profile
        except Exception as exc:
            result.warnings.append(f"Profiling skipped due to error: {exc}")
            logger.exception("Profile stage failed (soft)")

        return result

# Minimal schema fallback
# -------------------------
def _minimal_schema_fallback(*, df: pd.DataFrame, dataset_name: str, source_filename: Optional[str]):
    """
    Minimal schema used only when validate() crashes.
    Keeps your downstream steps alive.

    Requires your Pydantic models to be importable.
    """
    # Import inside to avoid circular imports if needed
    from uuid import uuid4
    from datetime import datetime
    from schemas import DatasetSchema, ColumnSchema  # adjust import path as needed

    cols = []
    for c in df.columns:
        s = df[c]
        non_null = s.dropna()
        sample = non_null.head(5).tolist() if not non_null.empty else []
        cols.append(
            ColumnSchema(
                name=str(c),
                dtype_raw=str(s.dtype),
                semantic_type="unknown",
                missing_count=int(s.isna().sum()),
                missing_ratio=float(s.isna().mean()) if len(s) else 0.0,
                unique_count=int(s.nunique(dropna=True)),
                is_constant=(int(s.nunique(dropna=True)) <= 1),
                is_empty=bool(non_null.empty),
                sample_values=sample,
            )
        )

    preview = df.head(5).where(pd.notna(df), None).to_dict(orient="records")

    return DatasetSchema(
        dataset_id=str(uuid4()),
        name=dataset_name,
        file_format="csv" if (source_filename or "").lower().endswith(".csv") else "excel",
        source_filename=source_filename,
        created_at=datetime.utcnow(),
        row_count=int(df.shape[0]),
        column_count=int(df.shape[1]),
        columns=cols,
        numeric_columns=[],
        categorical_columns=[],
        datetime_columns=[],
        boolean_columns=[],
        text_columns=[],
        unknown_columns=[str(c) for c in df.columns],
        preview_rows=preview,
    )


# -----------------------------
# Optional: resilient LLM call (Tableau spec generation)
# -----------------------------

class LLMError(Exception):
    """Raised for LLM failures (wrap provider exceptions into this)."""


def resilient_generate_tableau_spec(
    llm_call: Callable[[], dict],
    *,
    cache_get: Optional[Callable[[], Optional[dict]]] = None,
    cache_set: Optional[Callable[[dict], None]] = None,
) -> dict:
    """
    Retries + fallbacks for the LLM step that generates Tableau JSON/spec.

    Strategy:
    1) Retry transient failures (timeouts/rate-limit)
    2) If still failing, fallback to cached last-good spec (if provided)
    3) If no cache, return a minimal safe spec placeholder
    """
    llm_policy = RetryPolicy(
        max_attempts=3,
        base_delay_s=1.0,
        max_delay_s=10.0,
        backoff=2.0,
        jitter_s=0.5,
        retry_on=(TimeoutError, ConnectionError, LLMError),
    )

    try:
        spec = retry(llm_call, policy=llm_policy, op_name="LLM.generate_tableau_spec")
        if cache_set:
            try:
                cache_set(spec)
            except Exception as exc:
                logger.warning("Cache set failed (ignored): %s", exc)
        return spec

    except Exception as exc:
        logger.error("LLM generation failed. Using fallback. Reason: %s", exc)

    # Fallback 1: cached
    if cache_get:
        try:
            cached = cache_get()
            if cached:
                logger.info("Using cached Tableau spec fallback.")
                return cached
        except Exception as exc:
            logger.warning("Cache get failed (ignored): %s", exc)

    # Fallback 2: minimal safe spec (so UI doesn't crash)
    return {
        "version": "fallback_v1",
        "title": "Fallback Dashboard",
        "worksheets": [],
        "dashboards": [
            {
                "name": "Dashboard 1",
                "layout": [],
                "notes": "LLM generation failed; this is a minimal fallback spec."
            }
        ],
        "warnings": ["LLM failed; generated fallback spec."],
    }