# -*- coding: utf-8 -*-
"""Resuable UI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFaKBjq3YQmaiGNy0xFysXM0ergqPprw
"""

#Header Component
def _page_header():
    """Render the top navigation strip and title."""
    st.set_page_config(
        page_title="Tableau Dashboard Generator",
        page_icon="",
        layout="wide",
    )

    st.markdown(
        "<h2 style='margin-bottom:0'> AI Tableau Dashboard Generator</h2>"
        "<p style='color:grey; margin-top:0'>Upload data → Configure → Generate → Download</p>",
        unsafe_allow_html=True,
    )

    # breadcrumb-style nav
    cols = st.columns(len(PAGES))
    for i, page_key in enumerate(PAGES):
        label = PAGE_LABELS[page_key]
        is_current = (st.session_state.page == page_key)
        if is_current:
            cols[i].markdown(f"**▸ {label}**")
        else:
            cols[i].markdown(f"  {label}")

    st.divider()

#Navigation Component
def _go(page):
    st.session_state.page = page

#State Management Component
def _init_state():
    """Set defaults on first load."""
    defaults = {
        "page": "upload",
        "uploaded_file_path": None,
        "uploaded_file_name": None,
        "df_preview": None,
        "quality_quick": None,
        "config": {
            "provider": "gemini",
            "model_name": "gemini-3-flash-preview",
            "api_key": "",
            "endpoint_url": "",
        },
        "pipeline_result": None,
        "pipeline_running": False,
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v

#File Validation Component
def _validate_uploaded_file(uploaded):
    """Check extension and size. Returns (ok, error_msg)."""
    name = uploaded.name
    ext = Path(name).suffix.lower()
    if ext not in ALLOWED_EXTENSIONS:
        return False, f"Unsupported file type **{ext}**. Please upload a CSV or Excel file."

    size_mb = uploaded.size / (1024 * 1024)
    if size_mb > MAX_FILE_SIZE_MB:
        return False, f"File is {size_mb:.1f} MB — max allowed is {MAX_FILE_SIZE_MB} MB."

    return True, ""

import pandas as pd

#Data Preview Loader
def _load_preview(path: str, nrows=500) -> pd.DataFrame:
    """Quick load of the first N rows for the preview table."""
    ext = Path(path).suffix.lower()
    if ext == ".csv":
        return pd.read_csv(path, nrows=nrows)
    else:
        return pd.read_excel(path, nrows=nrows)

#Data Quality Component
def _quick_quality(df: pd.DataFrame) -> dict:
    """Lightweight quality stats computed purely in pandas."""
    total_cells = df.shape[0] * df.shape[1]
    missing = int(df.isnull().sum().sum())
    dupes = int(df.duplicated().sum())

    missing_pct = (missing / total_cells * 100) if total_cells else 0
    dupe_pct = (dupes / len(df) * 100) if len(df) else 0

    score = 100.0
    score -= missing_pct * 1.5
    score -= dupe_pct * 0.5
    score = max(0.0, min(100.0, score))

    return {
        "rows": df.shape[0],
        "cols": df.shape[1],
        "missing": missing,
        "missing_pct": round(missing_pct, 2),
        "dupes": dupes,
        "dupe_pct": round(dupe_pct, 2),
        "score": round(score, 1),
    }

import io
import logging

#Logging Component
LOG_BUFFER = io.StringIO()

def _setup_logging():
    """Wire up a stream handler that writes into LOG_BUFFER."""
    root = logging.getLogger()

    for h in root.handlers[:]:
        if getattr(h, "_streamlit_log_handler", False):
            root.removeHandler(h)

    handler = logging.StreamHandler(LOG_BUFFER)
    handler.setFormatter(logging.Formatter(
        "%(asctime)s  [%(levelname)s]  %(name)s — %(message)s",
        datefmt="%H:%M:%S",
    ))
    handler._streamlit_log_handler = True
    root.addHandler(handler)
    root.setLevel(logging.INFO)

#Error Handling Component
def _show_errors(result):
    errors = result.get("errors", [])
    if not errors:
        return

    with st.expander(f"⚠ {len(errors)} error(s) / warning(s)", expanded=True):
        for e in errors:
            stage = e.get("stage", "?")
            msg = e.get("message", "")
            recoverable = e.get("recoverable", True)

            if recoverable:
                st.warning(f"**[{stage}]** {msg}")
            else:
                st.error(f"**[{stage}]** {msg}")

!pip install streamlit
import streamlit as st

#Progress Tracking Component
STAGE_LABELS = {
    "pending":      "Waiting to start…",
    "validating":   "Validating data…",
    "profiling":    "Profiling columns…",
    "analyzing":    "Running AI analysis…",
    "recommending": "Choosing visualizations…",
    "generating":   "Building Tableau workbook…",
    "finalizing":   "Wrapping up…",
    "completed":    "Done!",
    "failed":       "Pipeline failed.",
}

progress_bar = st.progress(0, text="Starting pipeline…")
status_text = st.empty()

def on_progress(node_name, state):
    prog = state.get("progress", {})
    pct = prog.get("percent_complete", 0)
    stage = prog.get("current_stage", "pending")
    msg = prog.get("message", "")

    label = STAGE_LABELS.get(stage, stage)
    clamped = min(int(pct), 100)
    progress_bar.progress(clamped, text=f"{label}  ({clamped}%)")
    status_text.caption(msg)

#Reset Component
def _reset():
    """Clear everything and go back to upload."""
    for key in list(st.session_state.keys()):
        del st.session_state[key]

#Upload Page
def page_upload():
    st.subheader("Upload your dataset")
    uploaded = st.file_uploader(
        "Drag a CSV or Excel file here",
        type=["csv", "xlsx", "xls"],
        help="Max 200 MB. The file will be saved to a temp directory for processing.",
    )

#Configure Page
def page_configure():
    st.subheader("Configure generation settings")
#Process Page
def page_process():
    st.subheader("Generating your dashboard")
#Results Page
def page_results():
    st.subheader("Results")