# -*- coding: utf-8 -*-
"""schemas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPwNuTXnUxy_eix65EyE7bThOoGa_6I3
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field, ConfigDict, field_validator

# Existing recommender-side schemas

class VisualizationSpec(BaseModel):
    """
    High-level visualization recommendation produced by the
    visualization recommender.

    This is the INPUT to TableauWorkbookGenerator._plan_worksheets().
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(..., description="Human-readable chart title")
    chart_type: Literal[
        "bar",
        "line",
        "scatter",
        "histogram",
        "box",
        "heatmap",
        "pie",
        "table",
    ] = Field(..., description="Recommended chart type")

    x: Optional[str] = Field(
        default=None,
        description="Field mapped to x-axis / columns shelf"
    )
    y: Optional[str] = Field(
        default=None,
        description="Field mapped to y-axis / rows shelf"
    )
    group_by: Optional[List[str]] = Field(
        default=None,
        description="Optional grouping columns"
    )
    aggregation: Optional[Literal[
        "sum", "avg", "min", "max", "count", "median"
    ]] = Field(
        default=None,
        description="Aggregation to apply to numeric measures"
    )

    @field_validator("title")
    @classmethod
    def validate_title(cls, v: str) -> str:
        if not v:
            raise ValueError("Visualization title cannot be empty")
        return v


class DashboardSpec(BaseModel):
    """
    Recommender-side dashboard schema.

    This is what TableauWorkbookGenerator expects as the constructor input:
        dashboard_spec.visuals
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(..., description="Dashboard name")
    visuals: List[VisualizationSpec] = Field(
        default_factory=list,
        description="Recommended visualizations for the dashboard"
    )

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not v:
            raise ValueError("Dashboard name cannot be empty")
        return v


# Workbook generator internal schemas

class WorksheetSpec(BaseModel):
    """
    Concrete Tableau worksheet plan produced after converting a
    VisualizationSpec into Tableau shelf assignments.

    Used in TableauWorkbookGenerator._plan_worksheets()
    and later in XML generation.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(..., description="Worksheet name in Tableau")
    mark_type: Literal["Bar", "Line", "Circle", "Square", "Pie", "Text"] = Field(
        ...,
        description="Tableau mark type"
    )

    rows_shelf: List[str] = Field(
        default_factory=list,
        description="Fields placed on Rows shelf"
    )
    columns_shelf: List[str] = Field(
        default_factory=list,
        description="Fields placed on Columns shelf"
    )

    color_field: Optional[str] = Field(
        default=None,
        description="Field used for color encoding"
    )
    size_field: Optional[str] = Field(
        default=None,
        description="Field used for size encoding"
    )
    tooltip_fields: List[str] = Field(
        default_factory=list,
        description="Fields shown in tooltip"
    )

    aggregation: Optional[Literal["SUM", "AVG", "MIN", "MAX", "COUNT", "MEDIAN"]] = Field(
        default=None,
        description="Tableau aggregation used for measures"
    )

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not v:
            raise ValueError("Worksheet name cannot be empty")
        return v

    @field_validator("rows_shelf", "columns_shelf", "tooltip_fields")
    @classmethod
    def clean_field_lists(cls, v: List[str]) -> List[str]:
        return [item.strip() for item in v if item and item.strip()]


class WorkbookSpec(BaseModel):
    """
    Internal workbook plan used by TableauWorkbookGenerator after
    worksheet planning is complete.

    This is the object returned by _plan_worksheets().
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(..., description="Workbook/dashboard title")
    datasource_name: str = Field(
        ...,
        description="Internal Tableau datasource name"
    )
    worksheets: List[WorksheetSpec] = Field(
        default_factory=list,
        description="All worksheets in the workbook"
    )
    dashboard_width: int = Field(
        default=1200,
        ge=100,
        description="Dashboard canvas width in pixels"
    )
    dashboard_height: int = Field(
        default=900,
        ge=100,
        description="Dashboard canvas height in pixels"
    )

    @field_validator("name", "datasource_name")
    @classmethod
    def validate_required_strings(cls, v: str) -> str:
        if not v:
            raise ValueError("This field cannot be empty")
        return v